development:
    ANNOTATOR_FILTER:                      false
    ANNOTATOR_RICHTEXT:                    true
    ANNOTATOR_RICHTEXT_CONFIG:             undo redo | styleselect | bold italic | link image media | code
    ANNOTATOR_RICHTEXT_WITH_CATALOG:       undo redo | styleselect | bold italic | link image media | code | mellink melimage
    RUNTIMEERROR_EMAIL:                    example@example.com
    GOOGLE_VERIFICATION_CODE:
    DEFAULT_USER_GROUP: public
    GOOGLE_ANALYTICS_CODE:
    ENVIRONMENT_TAG:
    DEFAULT_USERS_CAN_CHOOSE_GROUPS: true
    DEFAULT_USERS_CAN_CONTROL_PERMISSIONS: true
    DEFAULT_USERS_CAN_CREATE_TEXTS: true
    DEFAULT_USERS_CAN_SEE_OTHERS_WORK: true
    GMAIL_USER: # to send user emails while in development
    GMAIL_PASS: # to send user emails while in development
    UNICORN_BACKLOG: 16
    # make the following the path to your local (or hosted) instance of the MIT-Annotation-Data-Store
    API_URL: http://localhost:5000/
    API_SECRET:
    API_CONSUMER: localhost
    CONFIRMATION_GRACE_PERIOD: 2
    ANNOTATOR_CATEGORIES:                   true
    ANNOTATOR_CUSTOM_SORT:                  true
    ANNOTATOR_RICHTEXT_WITH_CATALOG:        undo redo | styleselect | bold italic | link image media | code | mellink melimage
    CATALOG_ENABLED:                        true
    MEL_CATALOG_API:                        "http://mel-catalog.herokuapp.com/api"
    DEVISE_SECRET_KEY:                     blah-blah # use: `rails g secret` to generate a value
    GLOBAL_ALERT:                           "Global Alert Goes Here. Very important information!"
    ALERT_LEVEL:                            "success"
    # make the following the path to your local (or hosted) instance of the MEL-Catalog service
    CATALOG_ENABLED:                        true
    MEL_CATALOG_API:                        "http://localhost:4000/api"

production:
    DEFAULT_NEW_USER_GROUP: public
    GOOGLE_ANALYTICS_CODE:
    ENVIRONMENT_TAG: Welcome
    DEFAULT_USER_GROUP:
    DEFAULT_USERS_CAN_CHOOSE_GROUPS: false
    DEFAULT_USERS_CAN_CONTROL_PERMISSIONS: false
    DEFAULT_USERS_CAN_CREATE_TEXTS: false
    DEFAULT_USERS_CAN_SEE_OTHERS_WORK: false
    UNICORN_BACKLOG: 16
    # Url to a running instance of MIT-Annotation-data-store
    API_URL: http://path.to.your.api.com/
    # Shared secret key between the Annotation Studio and Annotation Store
    # Make up a <32 character random string
    API_SECRET:
    # domain name of the current website
    API_CONSUMER: http://your.site.domain.com
    CONFIRMATION_GRACE_PERIOD: 2
    GMAIL_USER: # or an SMTP account if you prefer
    GMAIL_PASS: # or an SMTP account if you prefer
    RUNTIMEERROR_EMAIL:                    example@example.com
    ANNOTATOR_CATEGORIES:                 false
    ANNOTATOR_CUSTOM_SORT:                false
    ANNOTATOR_FILTER:                     false
    ANNOTATOR_RICHTEXT:                   true
    ANNOTATOR_RICHTEXT_CONFIG:            undo redo | styleselect | bold italic | link image media | code
    DEVISE_SECRET_KEY:                    blah-blah # use: `rails g secret` to generate a value
    ANNOTATOR_RICHTEXT_WITH_CATALOG:       undo redo | styleselect | bold italic | link image media | code | mellink melimage
    CATALOG_ENABLED:                      true
    MEL_CATALOG_API:                      "http://mel-catalog.herokuapp.com/api"
