development:
    GOOGLE_VERIFICATION_CODE: 
    DEFAULT_USER_GROUP: 
    GOOGLE_ANALYTICS_CODE: 
    ENVIRONMENT_TAG: 
    API_URL: http://localhost:5000/api
    DEFAULT_USERS_CAN_CHOOSE_GROUPS: true
    DEFAULT_USERS_CAN_CONTROL_PERMISSIONS: true
    DEFAULT_USERS_CAN_CREATE_TEXTS: true
    DEFAULT_USERS_CAN_SEE_OTHERS_WORK: true
    GMAIL_USER: # to send user emails while in development
    GMAIL_PASS: # to send user emails while in development 
    UNICORN_BACKLOG: 16
    API_SECRET: 
    API_CONSUMER: localhost
    CONFIRMATION_GRACE_PERIOD: 2

production:
    DEFAULT_NEW_USER_GROUP: public
    GOOGLE_ANALYTICS_CODE:
    ENVIRONMENT_TAG: Welcome
    API_URL: http://path.to.your/api
    DEFAULT_USER_GROUP:
    DEFAULT_USERS_CAN_CHOOSE_GROUPS: false
    DEFAULT_USERS_CAN_CONTROL_PERMISSIONS: false
    DEFAULT_USERS_CAN_CREATE_TEXTS: false
    DEFAULT_USERS_CAN_SEE_OTHERS_WORK: false
    UNICORN_BACKLOG: 16
    API_SECRET:
    API_CONSUMER: app.annotationstudio.org
    CONFIRMATION_GRACE_PERIOD: 2
    GMAIL_USER: # or an SMTP account if you prefer
    GMAIL_PASS: # or an SMTP account if you prefer
