default:
  site_name:
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  brand: 'shared/default_brand'
public:
  site_name: Public
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
cove-studio:
  site_name: COVE
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: "COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website."
  site_color: '#279eb2'
  brand: 'shared/cove_brand'
staging-annotationstudio:
  site_name: MIT Staging
  welcome_message: "Welcome to Annotation Studio Staging at <strong>MIT</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#A31F34'
barnard:
  site_name: Barnard College
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Barnard College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#005596'
bucknell:
  site_name: Bucknell University
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Bucknell University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#00337F'
newhaven:
  site_name: University of New Haven
  welcome_message: "Welcome to Annotation Studio Staging at <strong>University of New Haven</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFD700'
stonybrook:
  site_name: Stonybrook
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Stony Brook University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#990000'
umb:
  site_name: U Mass Boston
  welcome_message: "Welcome to Annotation Studio Staging at <strong>University of Massachusetts, Boston</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#38197A'
vassar:
  site_name: vassar
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Vassar College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#800000'
washjeff:
  site_name: WashJeff
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Washington and Jefferson College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FF0000'
wheatoncollege:
  site_name: Wheaton College
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Wheaton College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFA5000'
wit:
  site_name: WIT
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Wentworth Institute of Technology</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFD700'
wlu:
  site_name: WLU
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Washington and Lee University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#F169E1'
