default:
  site_name:
  welcome_message: "Welcome to Annotation Studio"
  site_color: '#CCC'
public:
  site_name: Public
  welcome_message: "Welcome to Annotation Studio"
  site_color: '#CCC'
mit:
  site_name: MIT
  welcome_message: "Welcome to Annotation Studio at <strong>MIT</strong>"
  site_color: '#A31F34'
